### ISSUE TITLE
thanks :)

### ISSUE THREAD

**Issue by jquast** [dt-rush/pysshlm#3]
Saw your comment, `# god bless the author of blessed for their work in setting up sequence handling`

So happy to help! I have little time to improve it (I hope to add Windows support in cmd.exe someday, for example), I see some input-related issues like #2 maybe I can help with, best wishes and enjoy coding!

**Comment by dt-rush** [comment]
Ah that's awesome! Yeah thanks, I'm gonna take advantage of the positioning code as well (seems direct from blessings) to implement some nicer features like tab completion and proper backspacing, left-right arrow key movement when in line mode.

I'll probably get a chance to open a pycharm debugger on this soon and could see what I can see about the inner workings of inkey()

Cheers!

**Comment by jquast** [comment]
There are a number of readline-like libraries for python already, might save you a lot of trouble, my favorite one is python-prompt-toolkit, https://github.com/jonathanslenders/python-prompt-toolkit

Another, https://github.com/dajose/pyrepl
and, https://github.com/deadsy/py_linenoise
I feel like there are more, can't seem to locate them at the moment

If you want to go your own anyway, here looks like a great article, https://github.com/lihaoyi/blog/blob/master/post/11%20-%20Build%20your%20own%20Command%20Line%20with%20ANSI%20escape%20codes.md

Most importantly, have fun! terminal programming is one of my favorite, hope it becomes yours too!
